// Compiles a dart2wasm-generated main module from `source` which can then
// instantiatable via the `instantiate` method.
//
// `source` needs to be a `Response` object (or promise thereof) e.g. created
// via the `fetch()` JS API.
export async function compileStreaming(source) {
  const builtins = {builtins: ['js-string']};
  return new CompiledApp(
      await WebAssembly.compileStreaming(source, builtins), builtins);
}

// Compiles a dart2wasm-generated wasm modules from `bytes` which is then
// instantiatable via the `instantiate` method.
export async function compile(bytes) {
  const builtins = {builtins: ['js-string']};
  return new CompiledApp(await WebAssembly.compile(bytes, builtins), builtins);
}

// DEPRECATED: Please use `compile` or `compileStreaming` to get a compiled app,
// use `instantiate` method to get an instantiated app and then call
// `invokeMain` to invoke the main function.
export async function instantiate(modulePromise, importObjectPromise) {
  var moduleOrCompiledApp = await modulePromise;
  if (!(moduleOrCompiledApp instanceof CompiledApp)) {
    moduleOrCompiledApp = new CompiledApp(moduleOrCompiledApp);
  }
  const instantiatedApp = await moduleOrCompiledApp.instantiate(await importObjectPromise);
  return instantiatedApp.instantiatedModule;
}

// DEPRECATED: Please use `compile` or `compileStreaming` to get a compiled app,
// use `instantiate` method to get an instantiated app and then call
// `invokeMain` to invoke the main function.
export const invoke = (moduleInstance, ...args) => {
  moduleInstance.exports.$invokeMain(args);
}

class CompiledApp {
  constructor(module, builtins) {
    this.module = module;
    this.builtins = builtins;
  }

  // The second argument is an options object containing:
  // `loadDeferredModule` is a JS function that takes a module name matching a
  //   wasm file produced by the dart2wasm compiler and returns the bytes to
  //   load the module. These bytes can be in either a format supported by
  //   `WebAssembly.compile` or `WebAssembly.compileStreaming`.
  // `loadDynamicModule` is a JS function that takes two string names matching,
  //   in order, a wasm file produced by the dart2wasm compiler during dynamic
  //   module compilation and a corresponding js file produced by the same
  //   compilation. It should return a JS Array containing 2 elements. The first
  //   should be the bytes for the wasm module in a format supported by
  //   `WebAssembly.compile` or `WebAssembly.compileStreaming`. The second
  //   should be the result of using the JS 'import' API on the js file path.
  // `loadDeferredId` is a JS function that takes a string corresponding to a load
  //   ID generated by the compiler when 'load-ids' option is passed. Each load
  //   ID maps to one or more WASM modules produced by the compiler. This
  //   function should return an array of byte arrays corresponding to all the
  //   modules specified by that load ID. The arrays should be in a format
  //   supported by `WebAssembly.compile` or `WebAssembly.compileStreaming`.
  async instantiate(additionalImports,
      {loadDeferredModule, loadDynamicModule, loadDeferredId} = {}) {
    let dartInstance;

    // Prints to the console
    function printToConsole(value) {
      if (typeof dartPrint == "function") {
        dartPrint(value);
        return;
      }
      if (typeof console == "object" && typeof console.log != "undefined") {
        console.log(value);
        return;
      }
      if (typeof print == "function") {
        print(value);
        return;
      }

      throw "Unable to print message: " + value;
    }

    // A special symbol attached to functions that wrap Dart functions.
    const jsWrappedDartFunctionSymbol = Symbol("JSWrappedDartFunction");

    function finalizeWrapper(dartFunction, wrapped) {
      wrapped.dartFunction = dartFunction;
      wrapped[jsWrappedDartFunctionSymbol] = true;
      return wrapped;
    }

    // Imports
    const dart2wasm = {
            _1: (decoder, codeUnits) => decoder.decode(codeUnits),
      _2: () => new TextDecoder("utf-8", {fatal: true}),
      _3: () => new TextDecoder("utf-8", {fatal: false}),
      _4: (s) => +s,
      _5: x0 => new Uint8Array(x0),
      _6: (x0,x1,x2) => x0.set(x1,x2),
      _7: (x0,x1) => x0.transferFromImageBitmap(x1),
      _9: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._9(f,arguments.length,x0) }),
      _10: x0 => new window.FinalizationRegistry(x0),
      _11: (x0,x1,x2,x3) => x0.register(x1,x2,x3),
      _12: (x0,x1) => x0.unregister(x1),
      _13: (x0,x1,x2) => x0.slice(x1,x2),
      _14: (x0,x1) => x0.decode(x1),
      _15: (x0,x1) => x0.segment(x1),
      _16: () => new TextDecoder(),
      _18: x0 => x0.buffer,
      _19: x0 => x0.wasmMemory,
      _20: () => globalThis.window._flutter_skwasmInstance,
      _21: x0 => x0.rasterStartMilliseconds,
      _22: x0 => x0.rasterEndMilliseconds,
      _23: x0 => x0.imageBitmaps,
      _139: (x0,x1) => x0.appendChild(x1),
      _170: (x0,x1,x2) => x0.addEventListener(x1,x2),
      _171: (x0,x1,x2) => x0.removeEventListener(x1,x2),
      _172: (x0,x1) => new OffscreenCanvas(x0,x1),
      _173: x0 => x0.remove(),
      _174: (x0,x1) => x0.append(x1),
      _176: x0 => x0.unlock(),
      _177: x0 => x0.getReader(),
      _178: (x0,x1) => x0.item(x1),
      _179: x0 => x0.next(),
      _180: x0 => x0.now(),
      _181: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._181(f,arguments.length,x0) }),
      _182: (x0,x1) => x0.addListener(x1),
      _183: (x0,x1) => x0.removeListener(x1),
      _184: (x0,x1) => x0.matchMedia(x1),
      _185: (x0,x1) => x0.revokeObjectURL(x1),
      _186: x0 => x0.close(),
      _187: (x0,x1,x2,x3,x4) => ({type: x0,data: x1,premultiplyAlpha: x2,colorSpaceConversion: x3,preferAnimation: x4}),
      _188: x0 => new window.ImageDecoder(x0),
      _189: (x0,x1) => ({frameIndex: x0,completeFramesOnly: x1}),
      _190: (x0,x1) => x0.decode(x1),
      _191: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._191(f,arguments.length,x0) }),
      _192: (x0,x1,x2,x3) => x0.addEventListener(x1,x2,x3),
      _194: (x0,x1) => x0.getModifierState(x1),
      _195: x0 => x0.preventDefault(),
      _196: x0 => x0.stopPropagation(),
      _197: (x0,x1) => x0.removeProperty(x1),
      _198: (x0,x1) => x0.prepend(x1),
      _199: x0 => new Intl.Locale(x0),
      _200: (x0,x1) => x0.observe(x1),
      _201: x0 => x0.disconnect(),
      _202: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._202(f,arguments.length,x0) }),
      _203: (x0,x1) => x0.getAttribute(x1),
      _204: (x0,x1) => x0.contains(x1),
      _205: (x0,x1) => x0.querySelector(x1),
      _206: x0 => x0.blur(),
      _207: x0 => x0.hasFocus(),
      _208: (x0,x1) => x0.removeAttribute(x1),
      _209: (x0,x1,x2) => x0.insertBefore(x1,x2),
      _210: (x0,x1) => x0.hasAttribute(x1),
      _211: (x0,x1) => x0.getModifierState(x1),
      _212: (x0,x1) => x0.createTextNode(x1),
      _213: x0 => x0.getBoundingClientRect(),
      _214: (x0,x1) => x0.closest(x1),
      _651: x0 => new Uint8Array(x0),
      _655: () => globalThis.window.flutterConfiguration,
      _657: x0 => x0.assetBase,
      _662: x0 => x0.canvasKitMaximumSurfaces,
      _663: x0 => x0.debugShowSemanticsNodes,
      _664: x0 => x0.hostElement,
      _665: x0 => x0.multiViewEnabled,
      _666: x0 => x0.nonce,
      _668: x0 => x0.fontFallbackBaseUrl,
      _678: x0 => x0.console,
      _679: x0 => x0.devicePixelRatio,
      _680: x0 => x0.document,
      _681: x0 => x0.history,
      _682: x0 => x0.innerHeight,
      _683: x0 => x0.innerWidth,
      _684: x0 => x0.location,
      _685: x0 => x0.navigator,
      _686: x0 => x0.visualViewport,
      _687: x0 => x0.performance,
      _689: x0 => x0.URL,
      _691: (x0,x1) => x0.getComputedStyle(x1),
      _692: x0 => x0.screen,
      _693: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._693(f,arguments.length,x0) }),
      _694: (x0,x1) => x0.requestAnimationFrame(x1),
      _698: (x0,x1) => x0.warn(x1),
      _701: x0 => globalThis.parseFloat(x0),
      _702: () => globalThis.window,
      _703: () => globalThis.Intl,
      _704: () => globalThis.Symbol,
      _705: (x0,x1,x2,x3,x4) => globalThis.createImageBitmap(x0,x1,x2,x3,x4),
      _707: x0 => x0.clipboard,
      _708: x0 => x0.maxTouchPoints,
      _709: x0 => x0.vendor,
      _710: x0 => x0.language,
      _711: x0 => x0.platform,
      _712: x0 => x0.userAgent,
      _713: (x0,x1) => x0.vibrate(x1),
      _714: x0 => x0.languages,
      _715: x0 => x0.documentElement,
      _716: (x0,x1) => x0.querySelector(x1),
      _717: (x0,x1) => x0.querySelectorAll(x1),
      _719: (x0,x1) => x0.createElement(x1),
      _722: (x0,x1) => x0.createEvent(x1),
      _723: x0 => x0.activeElement,
      _726: x0 => x0.head,
      _727: x0 => x0.body,
      _728: (x0,x1) => { x0.title = x1 },
      _732: x0 => x0.visibilityState,
      _733: () => globalThis.document,
      _734: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._734(f,arguments.length,x0) }),
      _735: (x0,x1) => x0.dispatchEvent(x1),
      _743: x0 => x0.target,
      _745: x0 => x0.timeStamp,
      _746: x0 => x0.type,
      _748: (x0,x1,x2,x3) => x0.initEvent(x1,x2,x3),
      _755: x0 => x0.firstChild,
      _759: x0 => x0.parentElement,
      _761: (x0,x1) => { x0.textContent = x1 },
      _762: x0 => x0.parentNode,
      _764: (x0,x1) => x0.removeChild(x1),
      _765: x0 => x0.isConnected,
      _773: x0 => x0.clientHeight,
      _774: x0 => x0.clientWidth,
      _775: x0 => x0.offsetHeight,
      _776: x0 => x0.offsetWidth,
      _777: x0 => x0.id,
      _778: (x0,x1) => { x0.id = x1 },
      _781: (x0,x1) => { x0.spellcheck = x1 },
      _782: x0 => x0.tagName,
      _783: x0 => x0.style,
      _786: (x0,x1) => x0.querySelectorAll(x1),
      _787: (x0,x1,x2) => x0.setAttribute(x1,x2),
      _788: (x0,x1) => { x0.tabIndex = x1 },
      _789: x0 => x0.tabIndex,
      _790: (x0,x1) => x0.focus(x1),
      _791: x0 => x0.scrollTop,
      _792: (x0,x1) => { x0.scrollTop = x1 },
      _793: x0 => x0.scrollLeft,
      _794: (x0,x1) => { x0.scrollLeft = x1 },
      _795: x0 => x0.classList,
      _797: (x0,x1) => { x0.className = x1 },
      _799: (x0,x1) => x0.getElementsByClassName(x1),
      _800: x0 => x0.click(),
      _801: (x0,x1) => x0.attachShadow(x1),
      _804: x0 => x0.computedStyleMap(),
      _805: (x0,x1) => x0.get(x1),
      _811: (x0,x1) => x0.getPropertyValue(x1),
      _812: (x0,x1,x2,x3) => x0.setProperty(x1,x2,x3),
      _813: x0 => x0.offsetLeft,
      _814: x0 => x0.offsetTop,
      _815: x0 => x0.offsetParent,
      _817: (x0,x1) => { x0.name = x1 },
      _818: x0 => x0.content,
      _819: (x0,x1) => { x0.content = x1 },
      _823: (x0,x1) => { x0.src = x1 },
      _824: x0 => x0.naturalWidth,
      _825: x0 => x0.naturalHeight,
      _829: (x0,x1) => { x0.crossOrigin = x1 },
      _831: (x0,x1) => { x0.decoding = x1 },
      _832: x0 => x0.decode(),
      _837: (x0,x1) => { x0.nonce = x1 },
      _841: (x0,x1) => { x0.width = x1 },
      _844: (x0,x1) => { x0.height = x1 },
      _847: (x0,x1) => x0.getContext(x1),
      _914: x0 => x0.width,
      _915: x0 => x0.height,
      _917: (x0,x1) => x0.fetch(x1),
      _918: x0 => x0.status,
      _920: x0 => x0.body,
      _921: x0 => x0.arrayBuffer(),
      _924: x0 => x0.read(),
      _925: x0 => x0.value,
      _926: x0 => x0.done,
      _933: x0 => x0.name,
      _934: x0 => x0.x,
      _935: x0 => x0.y,
      _938: x0 => x0.top,
      _939: x0 => x0.right,
      _940: x0 => x0.bottom,
      _941: x0 => x0.left,
      _951: x0 => x0.height,
      _952: x0 => x0.width,
      _953: x0 => x0.scale,
      _954: (x0,x1) => { x0.value = x1 },
      _957: (x0,x1) => { x0.placeholder = x1 },
      _959: (x0,x1) => { x0.name = x1 },
      _960: x0 => x0.selectionDirection,
      _961: x0 => x0.selectionStart,
      _962: x0 => x0.selectionEnd,
      _965: x0 => x0.value,
      _967: (x0,x1,x2) => x0.setSelectionRange(x1,x2),
      _968: x0 => x0.readText(),
      _969: (x0,x1) => x0.writeText(x1),
      _971: x0 => x0.altKey,
      _972: x0 => x0.code,
      _973: x0 => x0.ctrlKey,
      _974: x0 => x0.key,
      _975: x0 => x0.keyCode,
      _976: x0 => x0.location,
      _977: x0 => x0.metaKey,
      _978: x0 => x0.repeat,
      _979: x0 => x0.shiftKey,
      _980: x0 => x0.isComposing,
      _982: x0 => x0.state,
      _983: (x0,x1) => x0.go(x1),
      _985: (x0,x1,x2,x3) => x0.pushState(x1,x2,x3),
      _986: (x0,x1,x2,x3) => x0.replaceState(x1,x2,x3),
      _987: x0 => x0.pathname,
      _988: x0 => x0.search,
      _989: x0 => x0.hash,
      _993: x0 => x0.state,
      _996: (x0,x1) => x0.createObjectURL(x1),
      _998: x0 => new Blob(x0),
      _1008: x0 => x0.matches,
      _1009: x0 => x0.matches,
      _1013: x0 => x0.relatedTarget,
      _1015: x0 => x0.clientX,
      _1016: x0 => x0.clientY,
      _1017: x0 => x0.offsetX,
      _1018: x0 => x0.offsetY,
      _1021: x0 => x0.button,
      _1022: x0 => x0.buttons,
      _1023: x0 => x0.ctrlKey,
      _1027: x0 => x0.pointerId,
      _1028: x0 => x0.pointerType,
      _1029: x0 => x0.pressure,
      _1030: x0 => x0.tiltX,
      _1031: x0 => x0.tiltY,
      _1032: x0 => x0.getCoalescedEvents(),
      _1035: x0 => x0.deltaX,
      _1036: x0 => x0.deltaY,
      _1037: x0 => x0.wheelDeltaX,
      _1038: x0 => x0.wheelDeltaY,
      _1039: x0 => x0.deltaMode,
      _1046: x0 => x0.changedTouches,
      _1049: x0 => x0.clientX,
      _1050: x0 => x0.clientY,
      _1053: x0 => x0.data,
      _1056: (x0,x1) => { x0.disabled = x1 },
      _1058: (x0,x1) => { x0.type = x1 },
      _1059: (x0,x1) => { x0.max = x1 },
      _1060: (x0,x1) => { x0.min = x1 },
      _1061: (x0,x1) => { x0.value = x1 },
      _1062: x0 => x0.value,
      _1063: x0 => x0.disabled,
      _1064: (x0,x1) => { x0.disabled = x1 },
      _1066: (x0,x1) => { x0.placeholder = x1 },
      _1068: (x0,x1) => { x0.name = x1 },
      _1069: (x0,x1) => { x0.autocomplete = x1 },
      _1071: x0 => x0.selectionDirection,
      _1072: x0 => x0.selectionStart,
      _1074: x0 => x0.selectionEnd,
      _1077: (x0,x1,x2) => x0.setSelectionRange(x1,x2),
      _1078: (x0,x1) => x0.add(x1),
      _1081: (x0,x1) => { x0.noValidate = x1 },
      _1082: (x0,x1) => { x0.method = x1 },
      _1083: (x0,x1) => { x0.action = x1 },
      _1108: x0 => x0.orientation,
      _1109: x0 => x0.width,
      _1110: x0 => x0.height,
      _1111: (x0,x1) => x0.lock(x1),
      _1130: x0 => new ResizeObserver(x0),
      _1133: (module,f) => finalizeWrapper(f, function(x0,x1) { return module.exports._1133(f,arguments.length,x0,x1) }),
      _1141: x0 => x0.length,
      _1142: x0 => x0.iterator,
      _1143: x0 => x0.Segmenter,
      _1144: x0 => x0.v8BreakIterator,
      _1145: (x0,x1) => new Intl.Segmenter(x0,x1),
      _1148: x0 => x0.language,
      _1149: x0 => x0.script,
      _1150: x0 => x0.region,
      _1168: x0 => x0.done,
      _1169: x0 => x0.value,
      _1170: x0 => x0.index,
      _1174: (x0,x1) => new Intl.v8BreakIterator(x0,x1),
      _1175: (x0,x1) => x0.adoptText(x1),
      _1176: x0 => x0.first(),
      _1177: x0 => x0.next(),
      _1178: x0 => x0.current(),
      _1191: x0 => x0.hostElement,
      _1192: x0 => x0.viewConstraints,
      _1195: x0 => x0.maxHeight,
      _1196: x0 => x0.maxWidth,
      _1197: x0 => x0.minHeight,
      _1198: x0 => x0.minWidth,
      _1199: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1199(f,arguments.length,x0) }),
      _1200: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1200(f,arguments.length,x0) }),
      _1201: (x0,x1) => ({addView: x0,removeView: x1}),
      _1204: x0 => x0.loader,
      _1205: () => globalThis._flutter,
      _1206: (x0,x1) => x0.didCreateEngineInitializer(x1),
      _1207: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1207(f,arguments.length,x0) }),
      _1208: (module,f) => finalizeWrapper(f, function() { return module.exports._1208(f,arguments.length) }),
      _1209: (x0,x1) => ({initializeEngine: x0,autoStart: x1}),
      _1212: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1212(f,arguments.length,x0) }),
      _1213: x0 => ({runApp: x0}),
      _1215: (x0,x1,x2) => x0.call(x1,x2),
      _1216: (module,f) => finalizeWrapper(f, function(x0,x1) { return module.exports._1216(f,arguments.length,x0,x1) }),
      _1217: x0 => new Promise(x0),
      _1218: x0 => x0.length,
      _1219: () => globalThis.window.ImageDecoder,
      _1220: x0 => x0.tracks,
      _1222: x0 => x0.completed,
      _1224: x0 => x0.image,
      _1230: x0 => x0.displayWidth,
      _1231: x0 => x0.displayHeight,
      _1232: x0 => x0.duration,
      _1235: x0 => x0.ready,
      _1236: x0 => x0.selectedTrack,
      _1237: x0 => x0.repetitionCount,
      _1238: x0 => x0.frameCount,
      _1294: (x0,x1,x2,x3) => x0.addEventListener(x1,x2,x3),
      _1295: (x0,x1,x2,x3) => x0.removeEventListener(x1,x2,x3),
      _1296: (x0,x1) => x0.createElement(x1),
      _1313: x0 => x0.click(),
      _1324: (x0,x1) => x0.query(x1),
      _1325: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1325(f,arguments.length,x0) }),
      _1326: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1326(f,arguments.length,x0) }),
      _1327: (x0,x1,x2) => ({enableHighAccuracy: x0,timeout: x1,maximumAge: x2}),
      _1328: (x0,x1,x2,x3) => x0.getCurrentPosition(x1,x2,x3),
      _1333: (x0,x1) => x0.getItem(x1),
      _1334: (x0,x1) => x0.removeItem(x1),
      _1335: (x0,x1,x2) => x0.setItem(x1,x2),
      _1349: (x0,x1) => x0.querySelector(x1),
      _1350: x0 => ({type: x0}),
      _1351: (x0,x1) => new Blob(x0,x1),
      _1352: x0 => globalThis.URL.createObjectURL(x0),
      _1353: (x0,x1) => x0.item(x1),
      _1354: () => new FileReader(),
      _1356: (x0,x1) => x0.readAsArrayBuffer(x1),
      _1357: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1357(f,arguments.length,x0) }),
      _1358: (x0,x1,x2) => x0.removeEventListener(x1,x2),
      _1359: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1359(f,arguments.length,x0) }),
      _1360: (x0,x1,x2) => x0.addEventListener(x1,x2),
      _1361: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1361(f,arguments.length,x0) }),
      _1362: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1362(f,arguments.length,x0) }),
      _1363: (x0,x1) => x0.removeChild(x1),
      _1364: x0 => new Blob(x0),
      _1365: x0 => globalThis.URL.revokeObjectURL(x0),
      _1367: Date.now,
      _1369: s => new Date(s * 1000).getTimezoneOffset() * 60,
      _1370: s => {
        if (!/^\s*[+-]?(?:Infinity|NaN|(?:\.\d+|\d+(?:\.\d*)?)(?:[eE][+-]?\d+)?)\s*$/.test(s)) {
          return NaN;
        }
        return parseFloat(s);
      },
      _1371: () => new Error().stack,
      _1372: () => typeof dartUseDateNowForTicks !== "undefined",
      _1373: () => 1000 * performance.now(),
      _1374: () => Date.now(),
      _1375: () => {
        // On browsers return `globalThis.location.href`
        if (globalThis.location != null) {
          return globalThis.location.href;
        }
        return null;
      },
      _1376: () => {
        return typeof process != "undefined" &&
               Object.prototype.toString.call(process) == "[object process]" &&
               process.platform == "win32"
      },
      _1377: () => new WeakMap(),
      _1378: (map, o) => map.get(o),
      _1379: (map, o, v) => map.set(o, v),
      _1380: (exn) => exn.toString(),
      _1381: (exn) => exn.stack,
      _1382: (exn) => {
        let stackString = exn.toString();
        let frames = stackString.split('\n');
        let drop = 2;
        if (frames[0] === 'Error') {
            drop += 1;
        }
        return frames.slice(drop).join('\n');
      },
      _1383: x0 => new WeakRef(x0),
      _1384: x0 => x0.deref(),
      _1385: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1385(f,arguments.length,x0) }),
      _1386: x0 => new FinalizationRegistry(x0),
      _1387: (x0,x1,x2,x3) => x0.register(x1,x2,x3),
      _1389: (x0,x1) => x0.unregister(x1),
      _1391: () => globalThis.WeakRef,
      _1392: () => globalThis.FinalizationRegistry,
      _1394: x0 => x0.call(),
      _1395: s => JSON.stringify(s),
      _1396: s => printToConsole(s),
      _1397: (o, p, r) => o.replaceAll(p, () => r),
      _1398: (o, p, r) => o.replace(p, () => r),
      _1399: Function.prototype.call.bind(String.prototype.toLowerCase),
      _1400: s => s.toUpperCase(),
      _1401: s => s.trim(),
      _1402: s => s.trimLeft(),
      _1403: s => s.trimRight(),
      _1404: (string, times) => string.repeat(times),
      _1405: Function.prototype.call.bind(String.prototype.indexOf),
      _1406: (s, p, i) => s.lastIndexOf(p, i),
      _1407: (string, token) => string.split(token),
      _1408: Object.is,
      _1412: (o, c) => o instanceof c,
      _1413: o => Object.keys(o),
      _1416: (o, a) => o + a,
      _1443: x0 => new Array(x0),
      _1445: x0 => x0.length,
      _1447: (x0,x1) => x0[x1],
      _1448: (x0,x1,x2) => { x0[x1] = x2 },
      _1451: (x0,x1,x2) => new DataView(x0,x1,x2),
      _1453: x0 => new Int8Array(x0),
      _1454: (x0,x1,x2) => new Uint8Array(x0,x1,x2),
      _1456: x0 => new Uint8ClampedArray(x0),
      _1458: x0 => new Int16Array(x0),
      _1460: x0 => new Uint16Array(x0),
      _1462: x0 => new Int32Array(x0),
      _1464: x0 => new Uint32Array(x0),
      _1466: x0 => new Float32Array(x0),
      _1468: x0 => new Float64Array(x0),
      _1492: x0 => x0.random(),
      _1493: (x0,x1) => x0.getRandomValues(x1),
      _1494: () => globalThis.crypto,
      _1495: () => globalThis.Math,
      _1508: (ms, c) =>
      setTimeout(() => dartInstance.exports.$invokeCallback(c),ms),
      _1509: (handle) => clearTimeout(handle),
      _1510: (ms, c) =>
      setInterval(() => dartInstance.exports.$invokeCallback(c), ms),
      _1511: (handle) => clearInterval(handle),
      _1512: (c) =>
      queueMicrotask(() => dartInstance.exports.$invokeCallback(c)),
      _1513: () => Date.now(),
      _1514: (s, m) => {
        try {
          return new RegExp(s, m);
        } catch (e) {
          return String(e);
        }
      },
      _1515: (x0,x1) => x0.exec(x1),
      _1516: (x0,x1) => x0.test(x1),
      _1517: x0 => x0.pop(),
      _1519: o => o === undefined,
      _1521: o => typeof o === 'function' && o[jsWrappedDartFunctionSymbol] === true,
      _1523: o => {
        const proto = Object.getPrototypeOf(o);
        return proto === Object.prototype || proto === null;
      },
      _1524: o => o instanceof RegExp,
      _1525: (l, r) => l === r,
      _1526: o => o,
      _1527: o => o,
      _1528: o => o,
      _1529: b => !!b,
      _1530: o => o.length,
      _1532: (o, i) => o[i],
      _1533: f => f.dartFunction,
      _1534: () => ({}),
      _1535: () => [],
      _1537: () => globalThis,
      _1538: (constructor, args) => {
        const factoryFunction = constructor.bind.apply(
            constructor, [null, ...args]);
        return new factoryFunction();
      },
      _1540: (o, p) => o[p],
      _1541: (o, p, v) => o[p] = v,
      _1542: (o, m, a) => o[m].apply(o, a),
      _1544: o => String(o),
      _1545: (p, s, f) => p.then(s, (e) => f(e, e === undefined)),
      _1546: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1546(f,arguments.length,x0) }),
      _1547: (module,f) => finalizeWrapper(f, function(x0,x1) { return module.exports._1547(f,arguments.length,x0,x1) }),
      _1548: o => {
        if (o === undefined) return 1;
        var type = typeof o;
        if (type === 'boolean') return 2;
        if (type === 'number') return 3;
        if (type === 'string') return 4;
        if (o instanceof Array) return 5;
        if (ArrayBuffer.isView(o)) {
          if (o instanceof Int8Array) return 6;
          if (o instanceof Uint8Array) return 7;
          if (o instanceof Uint8ClampedArray) return 8;
          if (o instanceof Int16Array) return 9;
          if (o instanceof Uint16Array) return 10;
          if (o instanceof Int32Array) return 11;
          if (o instanceof Uint32Array) return 12;
          if (o instanceof Float32Array) return 13;
          if (o instanceof Float64Array) return 14;
          if (o instanceof DataView) return 15;
        }
        if (o instanceof ArrayBuffer) return 16;
        // Feature check for `SharedArrayBuffer` before doing a type-check.
        if (globalThis.SharedArrayBuffer !== undefined &&
            o instanceof SharedArrayBuffer) {
            return 17;
        }
        if (o instanceof Promise) return 18;
        return 19;
      },
      _1549: o => [o],
      _1550: (o0, o1) => [o0, o1],
      _1551: (o0, o1, o2) => [o0, o1, o2],
      _1552: (o0, o1, o2, o3) => [o0, o1, o2, o3],
      _1553: (jsArray, jsArrayOffset, wasmArray, wasmArrayOffset, length) => {
        const getValue = dartInstance.exports.$wasmI8ArrayGet;
        for (let i = 0; i < length; i++) {
          jsArray[jsArrayOffset + i] = getValue(wasmArray, wasmArrayOffset + i);
        }
      },
      _1554: (jsArray, jsArrayOffset, wasmArray, wasmArrayOffset, length) => {
        const setValue = dartInstance.exports.$wasmI8ArraySet;
        for (let i = 0; i < length; i++) {
          setValue(wasmArray, wasmArrayOffset + i, jsArray[jsArrayOffset + i]);
        }
      },
      _1555: (jsArray, jsArrayOffset, wasmArray, wasmArrayOffset, length) => {
        const getValue = dartInstance.exports.$wasmI16ArrayGet;
        for (let i = 0; i < length; i++) {
          jsArray[jsArrayOffset + i] = getValue(wasmArray, wasmArrayOffset + i);
        }
      },
      _1556: (jsArray, jsArrayOffset, wasmArray, wasmArrayOffset, length) => {
        const setValue = dartInstance.exports.$wasmI16ArraySet;
        for (let i = 0; i < length; i++) {
          setValue(wasmArray, wasmArrayOffset + i, jsArray[jsArrayOffset + i]);
        }
      },
      _1557: (jsArray, jsArrayOffset, wasmArray, wasmArrayOffset, length) => {
        const getValue = dartInstance.exports.$wasmI32ArrayGet;
        for (let i = 0; i < length; i++) {
          jsArray[jsArrayOffset + i] = getValue(wasmArray, wasmArrayOffset + i);
        }
      },
      _1558: (jsArray, jsArrayOffset, wasmArray, wasmArrayOffset, length) => {
        const setValue = dartInstance.exports.$wasmI32ArraySet;
        for (let i = 0; i < length; i++) {
          setValue(wasmArray, wasmArrayOffset + i, jsArray[jsArrayOffset + i]);
        }
      },
      _1559: (jsArray, jsArrayOffset, wasmArray, wasmArrayOffset, length) => {
        const getValue = dartInstance.exports.$wasmF32ArrayGet;
        for (let i = 0; i < length; i++) {
          jsArray[jsArrayOffset + i] = getValue(wasmArray, wasmArrayOffset + i);
        }
      },
      _1560: (jsArray, jsArrayOffset, wasmArray, wasmArrayOffset, length) => {
        const setValue = dartInstance.exports.$wasmF32ArraySet;
        for (let i = 0; i < length; i++) {
          setValue(wasmArray, wasmArrayOffset + i, jsArray[jsArrayOffset + i]);
        }
      },
      _1561: (jsArray, jsArrayOffset, wasmArray, wasmArrayOffset, length) => {
        const getValue = dartInstance.exports.$wasmF64ArrayGet;
        for (let i = 0; i < length; i++) {
          jsArray[jsArrayOffset + i] = getValue(wasmArray, wasmArrayOffset + i);
        }
      },
      _1562: (jsArray, jsArrayOffset, wasmArray, wasmArrayOffset, length) => {
        const setValue = dartInstance.exports.$wasmF64ArraySet;
        for (let i = 0; i < length; i++) {
          setValue(wasmArray, wasmArrayOffset + i, jsArray[jsArrayOffset + i]);
        }
      },
      _1563: x0 => new ArrayBuffer(x0),
      _1564: s => {
        if (/[[\]{}()*+?.\\^$|]/.test(s)) {
            s = s.replace(/[[\]{}()*+?.\\^$|]/g, '\\$&');
        }
        return s;
      },
      _1566: x0 => x0.index,
      _1568: x0 => x0.flags,
      _1569: x0 => x0.multiline,
      _1570: x0 => x0.ignoreCase,
      _1571: x0 => x0.unicode,
      _1572: x0 => x0.dotAll,
      _1573: (x0,x1) => { x0.lastIndex = x1 },
      _1574: (o, p) => p in o,
      _1575: (o, p) => o[p],
      _1576: (o, p, v) => o[p] = v,
      _1578: x0 => x0.exports,
      _1579: (x0,x1) => globalThis.WebAssembly.instantiateStreaming(x0,x1),
      _1580: x0 => x0.instance,
      _1583: x0 => x0.buffer,
      _1586: x0 => x0.arrayBuffer(),
      _1588: x0 => x0.sqlite3_initialize(),
      _1590: (x0,x1,x2,x3,x4) => x0.sqlite3_open_v2(x1,x2,x3,x4),
      _1591: (x0,x1) => x0.sqlite3_close_v2(x1),
      _1592: (x0,x1,x2) => x0.sqlite3_extended_result_codes(x1,x2),
      _1593: (x0,x1) => x0.sqlite3_extended_errcode(x1),
      _1594: (x0,x1) => x0.sqlite3_errmsg(x1),
      _1595: (x0,x1) => x0.sqlite3_errstr(x1),
      _1596: (x0,x1) => x0.sqlite3_error_offset(x1),
      _1600: (x0,x1) => x0.sqlite3_last_insert_rowid(x1),
      _1601: (x0,x1) => x0.sqlite3_changes(x1),
      _1602: (x0,x1,x2,x3,x4,x5) => x0.sqlite3_exec(x1,x2,x3,x4,x5),
      _1603: (x0,x1) => x0.sqlite3_get_autocommit(x1),
      _1605: (x0,x1,x2,x3,x4,x5,x6) => x0.sqlite3_prepare_v3(x1,x2,x3,x4,x5,x6),
      _1606: (x0,x1) => x0.sqlite3_finalize(x1),
      _1607: (x0,x1) => x0.sqlite3_step(x1),
      _1608: (x0,x1) => x0.sqlite3_reset(x1),
      _1611: (x0,x1) => x0.sqlite3_column_count(x1),
      _1612: (x0,x1) => x0.sqlite3_bind_parameter_count(x1),
      _1614: (x0,x1,x2) => x0.sqlite3_column_name(x1,x2),
      _1615: (x0,x1,x2,x3) => x0.sqlite3_bind_double(x1,x2,x3),
      _1616: (x0,x1,x2,x3) => x0.sqlite3_bind_int64(x1,x2,x3),
      _1617: (x0,x1,x2) => x0.sqlite3_bind_null(x1,x2),
      _1618: (x0,x1,x2) => x0.sqlite3_column_blob(x1,x2),
      _1619: (x0,x1,x2) => x0.sqlite3_column_double(x1,x2),
      _1620: (x0,x1,x2) => x0.sqlite3_column_int64(x1,x2),
      _1621: (x0,x1,x2) => x0.sqlite3_column_text(x1,x2),
      _1622: (x0,x1,x2) => x0.sqlite3_column_bytes(x1,x2),
      _1623: (x0,x1,x2) => x0.sqlite3_column_type(x1,x2),
      _1642: (x0,x1) => x0.sqlite3session_delete(x1),
      _1646: (x0,x1) => x0.sqlite3changeset_finalize(x1),
      _1657: (x0,x1) => x0.dart_sqlite3_malloc(x1),
      _1658: (x0,x1) => x0.dart_sqlite3_free(x1),
      _1659: (x0,x1,x2,x3,x4) => x0.dart_sqlite3_bind_blob(x1,x2,x3,x4),
      _1660: (x0,x1,x2,x3,x4) => x0.dart_sqlite3_bind_text(x1,x2,x3,x4),
      _1661: (x0,x1,x2,x3) => x0.dart_sqlite3_register_vfs(x1,x2,x3),
      _1665: (x0,x1,x2) => x0.dart_sqlite3_updates(x1,x2),
      _1666: (x0,x1,x2) => x0.dart_sqlite3_commits(x1,x2),
      _1667: (x0,x1,x2) => x0.dart_sqlite3_rollbacks(x1,x2),
      _1669: (x0,x1,x2,x3) => x0.dart_sqlite3_db_config_int(x1,x2,x3),
      _1672: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1672(f,arguments.length,x0) }),
      _1673: (module,f) => finalizeWrapper(f, function(x0,x1) { return module.exports._1673(f,arguments.length,x0,x1) }),
      _1674: (module,f) => finalizeWrapper(f, function(x0,x1,x2,x3,x4) { return module.exports._1674(f,arguments.length,x0,x1,x2,x3,x4) }),
      _1675: (module,f) => finalizeWrapper(f, function(x0,x1,x2) { return module.exports._1675(f,arguments.length,x0,x1,x2) }),
      _1676: (module,f) => finalizeWrapper(f, function(x0,x1,x2,x3) { return module.exports._1676(f,arguments.length,x0,x1,x2,x3) }),
      _1677: (module,f) => finalizeWrapper(f, function(x0,x1,x2,x3) { return module.exports._1677(f,arguments.length,x0,x1,x2,x3) }),
      _1678: (module,f) => finalizeWrapper(f, function(x0,x1,x2) { return module.exports._1678(f,arguments.length,x0,x1,x2) }),
      _1679: (module,f) => finalizeWrapper(f, function(x0,x1) { return module.exports._1679(f,arguments.length,x0,x1) }),
      _1680: (module,f) => finalizeWrapper(f, function(x0,x1) { return module.exports._1680(f,arguments.length,x0,x1) }),
      _1681: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1681(f,arguments.length,x0) }),
      _1682: (module,f) => finalizeWrapper(f, function(x0,x1,x2,x3) { return module.exports._1682(f,arguments.length,x0,x1,x2,x3) }),
      _1683: (module,f) => finalizeWrapper(f, function(x0,x1,x2,x3) { return module.exports._1683(f,arguments.length,x0,x1,x2,x3) }),
      _1684: (module,f) => finalizeWrapper(f, function(x0,x1) { return module.exports._1684(f,arguments.length,x0,x1) }),
      _1685: (module,f) => finalizeWrapper(f, function(x0,x1) { return module.exports._1685(f,arguments.length,x0,x1) }),
      _1686: (module,f) => finalizeWrapper(f, function(x0,x1) { return module.exports._1686(f,arguments.length,x0,x1) }),
      _1687: (module,f) => finalizeWrapper(f, function(x0,x1) { return module.exports._1687(f,arguments.length,x0,x1) }),
      _1688: (module,f) => finalizeWrapper(f, function(x0,x1) { return module.exports._1688(f,arguments.length,x0,x1) }),
      _1689: (module,f) => finalizeWrapper(f, function(x0,x1) { return module.exports._1689(f,arguments.length,x0,x1) }),
      _1690: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1690(f,arguments.length,x0) }),
      _1691: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1691(f,arguments.length,x0) }),
      _1692: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1692(f,arguments.length,x0) }),
      _1693: (module,f) => finalizeWrapper(f, function(x0,x1,x2,x3,x4) { return module.exports._1693(f,arguments.length,x0,x1,x2,x3,x4) }),
      _1694: (module,f) => finalizeWrapper(f, function(x0,x1,x2,x3) { return module.exports._1694(f,arguments.length,x0,x1,x2,x3) }),
      _1695: (module,f) => finalizeWrapper(f, function(x0,x1,x2,x3) { return module.exports._1695(f,arguments.length,x0,x1,x2,x3) }),
      _1696: (module,f) => finalizeWrapper(f, function(x0,x1,x2,x3) { return module.exports._1696(f,arguments.length,x0,x1,x2,x3) }),
      _1697: (module,f) => finalizeWrapper(f, function(x0,x1) { return module.exports._1697(f,arguments.length,x0,x1) }),
      _1698: (module,f) => finalizeWrapper(f, function(x0,x1) { return module.exports._1698(f,arguments.length,x0,x1) }),
      _1699: (module,f) => finalizeWrapper(f, function(x0,x1,x2,x3,x4) { return module.exports._1699(f,arguments.length,x0,x1,x2,x3,x4) }),
      _1700: (module,f) => finalizeWrapper(f, function(x0,x1) { return module.exports._1700(f,arguments.length,x0,x1) }),
      _1701: (module,f) => finalizeWrapper(f, function(x0,x1) { return module.exports._1701(f,arguments.length,x0,x1) }),
      _1702: (module,f) => finalizeWrapper(f, function(x0,x1,x2) { return module.exports._1702(f,arguments.length,x0,x1,x2) }),
      _1706: x0 => new URL(x0),
      _1707: (x0,x1) => new URL(x0,x1),
      _1708: (x0,x1) => globalThis.fetch(x0,x1),
      _1712: (x0,x1) => new SharedWorker(x0,x1),
      _1713: x0 => new Worker(x0),
      _1731: (x0,x1) => globalThis.IDBKeyRange.bound(x0,x1),
      _1732: (x0,x1,x2) => x0.open(x1,x2),
      _1733: x0 => ({autoIncrement: x0}),
      _1734: (x0,x1,x2) => x0.createObjectStore(x1,x2),
      _1735: x0 => ({unique: x0}),
      _1736: (x0,x1,x2,x3) => x0.createIndex(x1,x2,x3),
      _1737: (x0,x1) => x0.createObjectStore(x1),
      _1738: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1738(f,arguments.length,x0) }),
      _1740: (x0,x1,x2) => x0.transaction(x1,x2),
      _1741: (x0,x1) => x0.objectStore(x1),
      _1743: (x0,x1) => x0.index(x1),
      _1744: x0 => x0.openKeyCursor(),
      _1745: (x0,x1) => x0.getKey(x1),
      _1746: (x0,x1) => ({name: x0,length: x1}),
      _1747: (x0,x1) => x0.put(x1),
      _1748: (x0,x1) => x0.get(x1),
      _1749: (x0,x1) => x0.openCursor(x1),
      _1750: x0 => globalThis.IDBKeyRange.only(x0),
      _1751: (x0,x1,x2) => x0.put(x1,x2),
      _1752: (x0,x1) => x0.update(x1),
      _1753: (x0,x1) => x0.delete(x1),
      _1756: x0 => x0.name,
      _1757: x0 => x0.length,
      _1762: x0 => x0.continue(),
      _1763: () => globalThis.indexedDB,
      _1776: x0 => globalThis.BigInt(x0),
      _1777: x0 => globalThis.Number(x0),
      _1805: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1805(f,arguments.length,x0) }),
      _1814: () => new AbortController(),
      _1815: x0 => x0.abort(),
      _1816: (x0,x1,x2,x3,x4,x5) => ({method: x0,headers: x1,body: x2,credentials: x3,redirect: x4,signal: x5}),
      _1817: (x0,x1) => globalThis.fetch(x0,x1),
      _1818: (x0,x1) => x0.get(x1),
      _1819: (module,f) => finalizeWrapper(f, function(x0,x1,x2) { return module.exports._1819(f,arguments.length,x0,x1,x2) }),
      _1820: (x0,x1) => x0.forEach(x1),
      _1821: x0 => x0.getReader(),
      _1822: x0 => x0.cancel(),
      _1823: x0 => x0.read(),
      _1824: (x0,x1) => x0.key(x1),
      _1825: o => o instanceof Array,
      _1827: (a, i) => a.splice(i, 1)[0],
      _1830: a => a.pop(),
      _1831: (a, i) => a.splice(i, 1),
      _1833: (a, s, e) => a.slice(s, e),
      _1835: (a, b) => a == b ? 0 : (a > b ? 1 : -1),
      _1836: a => a.length,
      _1838: (a, i) => a[i],
      _1839: (a, i, v) => a[i] = v,
      _1841: o => {
        if (o instanceof ArrayBuffer) return 0;
        if (globalThis.SharedArrayBuffer !== undefined &&
            o instanceof SharedArrayBuffer) {
          return 1;
        }
        return 2;
      },
      _1842: (o, offsetInBytes, lengthInBytes) => {
        var dst = new ArrayBuffer(lengthInBytes);
        new Uint8Array(dst).set(new Uint8Array(o, offsetInBytes, lengthInBytes));
        return new DataView(dst);
      },
      _1844: o => o instanceof Uint8Array,
      _1845: (o, start, length) => new Uint8Array(o.buffer, o.byteOffset + start, length),
      _1846: o => o instanceof Int8Array,
      _1847: (o, start, length) => new Int8Array(o.buffer, o.byteOffset + start, length),
      _1848: o => o instanceof Uint8ClampedArray,
      _1849: (o, start, length) => new Uint8ClampedArray(o.buffer, o.byteOffset + start, length),
      _1850: o => o instanceof Uint16Array,
      _1851: (o, start, length) => new Uint16Array(o.buffer, o.byteOffset + start, length),
      _1852: o => o instanceof Int16Array,
      _1853: (o, start, length) => new Int16Array(o.buffer, o.byteOffset + start, length),
      _1854: o => o instanceof Uint32Array,
      _1855: (o, start, length) => new Uint32Array(o.buffer, o.byteOffset + start, length),
      _1856: o => o instanceof Int32Array,
      _1857: (o, start, length) => new Int32Array(o.buffer, o.byteOffset + start, length),
      _1859: (o, start, length) => new BigInt64Array(o.buffer, o.byteOffset + start, length),
      _1860: o => o instanceof Float32Array,
      _1861: (o, start, length) => new Float32Array(o.buffer, o.byteOffset + start, length),
      _1862: o => o instanceof Float64Array,
      _1863: (o, start, length) => new Float64Array(o.buffer, o.byteOffset + start, length),
      _1864: (t, s) => t.set(s),
      _1865: l => new DataView(new ArrayBuffer(l)),
      _1866: (o) => new DataView(o.buffer, o.byteOffset, o.byteLength),
      _1867: o => o.byteLength,
      _1868: o => o.buffer,
      _1869: o => o.byteOffset,
      _1870: Function.prototype.call.bind(Object.getOwnPropertyDescriptor(DataView.prototype, 'byteLength').get),
      _1871: (b, o) => new DataView(b, o),
      _1872: (b, o, l) => new DataView(b, o, l),
      _1873: Function.prototype.call.bind(DataView.prototype.getUint8),
      _1874: Function.prototype.call.bind(DataView.prototype.setUint8),
      _1875: Function.prototype.call.bind(DataView.prototype.getInt8),
      _1876: Function.prototype.call.bind(DataView.prototype.setInt8),
      _1877: Function.prototype.call.bind(DataView.prototype.getUint16),
      _1878: Function.prototype.call.bind(DataView.prototype.setUint16),
      _1879: Function.prototype.call.bind(DataView.prototype.getInt16),
      _1880: Function.prototype.call.bind(DataView.prototype.setInt16),
      _1881: Function.prototype.call.bind(DataView.prototype.getUint32),
      _1882: Function.prototype.call.bind(DataView.prototype.setUint32),
      _1883: Function.prototype.call.bind(DataView.prototype.getInt32),
      _1884: Function.prototype.call.bind(DataView.prototype.setInt32),
      _1887: Function.prototype.call.bind(DataView.prototype.getBigInt64),
      _1888: Function.prototype.call.bind(DataView.prototype.setBigInt64),
      _1889: Function.prototype.call.bind(DataView.prototype.getFloat32),
      _1890: Function.prototype.call.bind(DataView.prototype.setFloat32),
      _1891: Function.prototype.call.bind(DataView.prototype.getFloat64),
      _1892: Function.prototype.call.bind(DataView.prototype.setFloat64),
      _1893: Function.prototype.call.bind(Number.prototype.toString),
      _1894: Function.prototype.call.bind(BigInt.prototype.toString),
      _1895: Function.prototype.call.bind(Number.prototype.toString),
      _1896: (d, digits) => d.toFixed(digits),
      _2063: (x0,x1) => { x0.draggable = x1 },
      _2079: x0 => x0.style,
      _2438: (x0,x1) => { x0.download = x1 },
      _2463: (x0,x1) => { x0.href = x1 },
      _3008: (x0,x1) => { x0.accept = x1 },
      _3022: x0 => x0.files,
      _3048: (x0,x1) => { x0.multiple = x1 },
      _3066: (x0,x1) => { x0.type = x1 },
      _3785: () => globalThis.window,
      _3825: x0 => x0.document,
      _3847: x0 => x0.navigator,
      _4111: x0 => x0.localStorage,
      _4215: x0 => x0.geolocation,
      _4218: x0 => x0.mediaDevices,
      _4220: x0 => x0.permissions,
      _4234: x0 => x0.userAgent,
      _4438: x0 => x0.length,
      _6383: x0 => x0.signal,
      _6438: x0 => x0.baseURI,
      _6444: x0 => x0.firstChild,
      _6455: () => globalThis.document,
      _6870: (x0,x1) => { x0.id = x1 },
      _6897: x0 => x0.children,
      _8216: x0 => x0.value,
      _8218: x0 => x0.done,
      _8382: x0 => x0.size,
      _8383: x0 => x0.type,
      _8389: x0 => x0.name,
      _8395: x0 => x0.length,
      _8400: x0 => x0.result,
      _8896: x0 => x0.url,
      _8898: x0 => x0.status,
      _8900: x0 => x0.statusText,
      _8901: x0 => x0.headers,
      _8902: x0 => x0.body,
      _9289: x0 => x0.state,
      _10353: x0 => x0.result,
      _10354: x0 => x0.error,
      _10365: (x0,x1) => { x0.onupgradeneeded = x1 },
      _10367: x0 => x0.oldVersion,
      _10446: x0 => x0.key,
      _10447: x0 => x0.primaryKey,
      _10449: x0 => x0.value,
      _10587: x0 => x0.coords,
      _10588: x0 => x0.timestamp,
      _10590: x0 => x0.accuracy,
      _10591: x0 => x0.latitude,
      _10592: x0 => x0.longitude,
      _10593: x0 => x0.altitude,
      _10594: x0 => x0.altitudeAccuracy,
      _10595: x0 => x0.heading,
      _10596: x0 => x0.speed,
      _10597: x0 => x0.code,
      _10598: x0 => x0.message,
      _11284: (x0,x1) => { x0.display = x1 },
      _12506: x0 => x0.name,

    };

    const baseImports = {
      dart2wasm: dart2wasm,
      Math: Math,
      Date: Date,
      Object: Object,
      Array: Array,
      Reflect: Reflect,
      WebAssembly: {
        JSTag: WebAssembly.JSTag,
      },
      "": new Proxy({}, { get(_, prop) { return prop; } }),

    };

    const jsStringPolyfill = {
      "charCodeAt": (s, i) => s.charCodeAt(i),
      "compare": (s1, s2) => {
        if (s1 < s2) return -1;
        if (s1 > s2) return 1;
        return 0;
      },
      "concat": (s1, s2) => s1 + s2,
      "equals": (s1, s2) => s1 === s2,
      "fromCharCode": (i) => String.fromCharCode(i),
      "length": (s) => s.length,
      "substring": (s, a, b) => s.substring(a, b),
      "fromCharCodeArray": (a, start, end) => {
        if (end <= start) return '';

        const read = dartInstance.exports.$wasmI16ArrayGet;
        let result = '';
        let index = start;
        const chunkLength = Math.min(end - index, 500);
        let array = new Array(chunkLength);
        while (index < end) {
          const newChunkLength = Math.min(end - index, 500);
          for (let i = 0; i < newChunkLength; i++) {
            array[i] = read(a, index++);
          }
          if (newChunkLength < chunkLength) {
            array = array.slice(0, newChunkLength);
          }
          result += String.fromCharCode(...array);
        }
        return result;
      },
      "intoCharCodeArray": (s, a, start) => {
        if (s === '') return 0;

        const write = dartInstance.exports.$wasmI16ArraySet;
        for (var i = 0; i < s.length; ++i) {
          write(a, start++, s.charCodeAt(i));
        }
        return s.length;
      },
      "test": (s) => typeof s == "string",
    };


    

    dartInstance = await WebAssembly.instantiate(this.module, {
      ...baseImports,
      ...additionalImports,
      
      "wasm:js-string": jsStringPolyfill,
    });
    dartInstance.exports.$setThisModule(dartInstance);

    return new InstantiatedApp(this, dartInstance);
  }
}

class InstantiatedApp {
  constructor(compiledApp, instantiatedModule) {
    this.compiledApp = compiledApp;
    this.instantiatedModule = instantiatedModule;
  }

  // Call the main function with the given arguments.
  invokeMain(...args) {
    this.instantiatedModule.exports.$invokeMain(args);
  }
}
